Port to API V8.
Kraigie/nostrum pull request #259
Opened 2021-07-17 20:10 UTC by jchristgit

This is based on the official changelog, found at
https://discord.com/developers/docs/change-log#api-and-gateway-v8.

The following user-facing changes are introduced:

- Updating the permission overwrite `type` type and documentation. Code using
  permission overwrites may need changing from the literal `"role"` and
  `"user"` wordings to the new number-based format.
- Remove `game` field usages in the presence cache in favour of `activities`.
- Remove `embed_enabled` and `embed_channel_id` from `Nostrum.Struct.Guild`
  (`widget_enabled` and `widget_channel_id`, the documented alternatives, are
  already present).

2021-08-09 18:28 UTC, jchristgit commented
This needs some more testing, I forgot a local stash here with the ratelimiter.

2021-08-09 18:52 UTC, jchristgit commented
Thank you pixel

2021-08-22 11:51 UTC, jb3 requested changes

2021-08-22 11:51 UTC, jb3 commented on lib/nostrum/api/ratelimiter.ex
> +    truncated = :erlang.trunc(timeout)
```suggestion
    truncated = :erlang.ceil(timeout)
```

2021-08-22 11:54 UTC, jb3 approved these changes

2021-09-03 17:53 UTC, jchristgit commented
Thanks for the review 🙂

2021-09-03 17:53 UTC, merged