Add Joseph and me to maintainers.
Kraigie/nostrum pull request #263
Opened 2021-07-17 23:52 UTC by jchristgit

2021-07-18 23:19 UTC, Kraigie approved these changes
Yeah I guess so

2021-07-19 00:09 UTC, jb3 requested changes

2021-07-19 00:09 UTC, jb3 commented on mix.exs
> +      maintainers: ["Craig Dazey", "Johannes Christ", "Joseph Banks"],
I'm Joe.
```suggestion
      maintainers: ["Craig Dazey", "Johannes Christ", "Joe Banks"],
```

2021-07-19 17:41 UTC, jchristgit commented
Thanks!

2021-07-19 17:42 UTC, merged