Enable component parsing.
Kraigie/nostrum pull request #357
Opened 2021-11-04 13:08 UTC by jchristgit

Define component type and re-enable parsing of message components.

Fixes #323.

2021-12-11 12:56 UTC, jchristgit commented
Hi @jb3 or @Kraigie, does one of you have time to review this this weekend?

2021-12-12 23:01 UTC, Th3-M4jor requested changes
Some minor things in the typespec that need fixing, as well as a `?` in a name that shouldn't be present.

2021-12-13 18:04 UTC, jchristgit commented
@Th3-M4jor the `?` was intentional to adhere to the Elixir "standard" of naming these fields. Should we keep it, or is this confusing?

2021-12-13 18:16 UTC, Th3-M4jor commented
I'm of the opinion we should try to mirror the official api docs as much as possible with our field names.

2021-12-13 18:23 UTC, jchristgit commented
Fair enough 👍

2021-12-13 18:23 UTC, jchristgit commented on lib/nostrum/struct/message/component.ex
> +          disabled?: disabled?(),
```suggestion
          disabled: disabled(),
```

2021-12-13 18:23 UTC, jchristgit commented on lib/nostrum/struct/message/component.ex
> +      disabled?: map[:disabled],
```suggestion
      disabled: map[:disabled],
```

2021-12-18 15:33 UTC, jb3 approved these changes
LGTM! Some of the markdown links wrapping onto newlines is a bit peculiar but I get why you've done it.

2021-12-18 15:35 UTC, merged

2021-12-18 15:35 UTC, jb3 commented
Thanks!