Declutter multipart functionality in api.
Kraigie/nostrum pull request #412
Opened 2022-03-15 17:35 UTC by BrandtHill

Remove buggy and now unused code that was causing some issues when moving from .5 rc to latest
Make request_multipart useful, removing duplicate code to make multipart and file handling easier

Additionally:

- fix spec for request_multipart
- fix bug where execute_webhook and edit_webhook message wasn’t casting to `Message` struct
- make internal function private
- silently handle combining `:embed` and `:embeds` similarly to `:file` and `:files`
- make file form name `files[n]` where `n` begins at 0 according to most recent docs
- support files for all applicable message editing functions

2022-03-15 19:30 UTC, Th3-M4jor requested changes

2022-03-15 19:30 UTC, Th3-M4jor commented on lib/nostrum/api.ex
> +      |> Jason.encode_to_iodata!()
Could probably simplify this to
```elixir
{files, body} = combine_files(body) |> Map.pop!(:files)

json = body |> Jason.encode_to_iodata!()
```

Other than that, this looks good to me.

2022-03-16 18:08 UTC, BrandtHill commented
Btw please test these. I’ve been writing this on my phone.

2022-03-17 00:44 UTC, BrandtHill commented
Fixed the create_interaction_response, could you test again?

2022-03-17 03:34 UTC, Th3-M4jor commented
Tested and it works, but now `Api.create_followup_message!/3` is throwing a dialyzer error on my machine. Saying the function call will not succeed.

2022-03-17 04:07 UTC, BrandtHill commented
> Tested and it works, but now `Api.create_followup_message!/3` is throwing a dialyzer error on my machine. Saying the function call will not succeed.

I think it was the request_multipart spec which I just fixed

2022-03-17 04:30 UTC, Th3-M4jor commented
I found the issue, `Api.execute_webhook` isn't decoding the response into a Message struct, it needs a `|> handle_request_with_decode({:struct, Message})`

2022-03-18 19:37 UTC, jchristgit approved these changes
Deleted code ✅ 

Thanks!

2022-03-18 19:37 UTC, merged

2022-03-18 19:37 UTC, jchristgit commented
Thanks!