Only attempt resume if the gateway says we can
Kraigie/nostrum pull request #566
Opened 2024-04-29 16:56 UTC by jchristgit

Per [1] and [2], if the `d` field is set to `true` we may attempt to
resume again with the same session, otherwise we should not. nostrum
would previously loop on trying to resume on the same session after an
invalid session was sent, and the behaviour of simply sending an
identify payload did not work as expected. When the session that we try
to resume with is invalid, perform a reconnect and do the whole
handshake, greeting and meeting the parents thing all over again.

[1]: https://discord.com/developers/docs/topics/gateway-events#invalid-session
[2]: https://discord.com/developers/docs/topics/gateway#resuming

2024-05-03 20:26 UTC, jb3 requested changes
This PR introduces some warnings of unused variables (`can_resume?`), can we confirm if that is intentional and amend if not? (I am happy to fix this if you can't)

2024-05-03 20:41 UTC, broman approved these changes

2024-05-04 05:21 UTC, jchristgit commented
> This PR introduces some warnings of unused variables (can_resume?), can we confirm if that is intentional and amend if not? (I am happy to fix this if you can't right now)

it's intentional although I haven't seen the warning until now. I will update this to underscore it

2024-05-04 12:50 UTC, jb3 approved these changes

2024-05-04 12:51 UTC, merged

2024-05-04 12:51 UTC, jb3 commented
Thanks!