Add new guild attributes
Kraigie/nostrum pull request #585
Opened 2024-05-05 19:11 UTC by jb3

Adds a heap of guild attributes upstream from Discord that we had not yet added to the guild struct.

Details of new attributes are contained within the added typedocs in the changelog, for brevity I will not list them again here.

2024-05-06 05:55 UTC, jchristgit requested changes
Looks very good. Some minor nitpicks.

2024-05-06 05:55 UTC, jchristgit commented on lib/nostrum/struct/guild.ex
> +  Use `Nostrum.Struct.Guild.SystemChannelFlags` to parse.
should this reference a function?

2024-05-06 05:55 UTC, jchristgit commented on lib/nostrum/struct/guild.ex
> +  @type max_members :: pos_integer() | nil
When are these `nil`? When are they not?

2024-05-06 05:55 UTC, jchristgit commented on lib/nostrum/struct/guild.ex
> +  @type premium_subscription_count :: pos_integer() | nil
This is also nonintuitive, why would this be `nil`? Wouldn't the "default" be `0`? Should we post-process it?

2024-05-06 05:55 UTC, jchristgit commented on lib/nostrum/struct/guild.ex
> +  @type max_stage_video_channel_users :: pos_integer() | nil
When are these `nil`? Can we document it? Or does `nil` simply mean "no limit"? Should we document that?

2024-05-06 05:55 UTC, jchristgit commented on lib/nostrum/struct/guild.ex
> +  Returns the URL of the guild's banner, or `nil` if no splash.
```suggestion
  Returns the URL of the guild's banner, or `nil` if no banner has been set.
```

2024-05-06 05:55 UTC, jchristgit commented on lib/nostrum/struct/guild/system_channel_flags.ex
> +  Struct representing the flags on a guilds system channel
```suggestion
  Struct representing the flags on a guild's system channel
```

2024-05-06 18:24 UTC, jb3 commented on lib/nostrum/struct/guild.ex
> +  Use `Nostrum.Struct.Guild.SystemChannelFlags` to parse.
I've updated the wording on this a bit.

2024-05-07 05:09 UTC, jchristgit approved these changes
Thanks!

2024-05-07 05:09 UTC, merged