feat(shard): manually shard connect and reconnect
Kraigie/nostrum pull request #596
Opened 2024-05-15 13:37 UTC by tignear

This PR provides the user with functions to connect/reconnect/disconnect to the gateway.
In our use case, this allows for zero downtime updates.
This would also advance Issue #542.

```elixir
# node 1
{gateway,_} = Nostrum.Util.gateway()
Nostrum.Shard.Supervisor.connect(gateway,0,1) 
info = Nostrum.Shard.Supervisor.disconnect(0)

# node2
Nostrum.Shard.Supervisor.reconnect(info)
```

2024-05-18 06:33 UTC, jb3 requested changes
Thank you for the contribution! This is a really cool feature!

I've tested it locally and all seems to be working solid, my only request is documentation on the new public facing APIs that enable this functionality.

It doesn't need to be incredibly comprehensive but an overview of what happens, what is returned and maybe a little overview of "how it works" (i.e. that it stores the resume information and then opens a new connection with that RESUME payload).

2024-05-22 18:38 UTC, jb3 approved these changes
Looks good!

2024-05-22 18:51 UTC, merged

2024-05-22 18:52 UTC, jb3 commented
Thanks!

2024-05-22 18:57 UTC, broman commented
Nice! This looks really good! Nostrum!